/**
 * Static MoSPI and Aviation Reference Constants.
 * Strictly ZERO synthetic/demo/mock data generators.
 */

import { Route, Airline, DataSource, AdvanceWindow } from '../src/types/index.ts';

export const ROUTE_BASKET: Route[] = [
  {
    id: 'route-1',
    code: 'DEL-BOM',
    origin: 'DEL',
    originCity: 'New Delhi (IGI)',
    destination: 'BOM',
    destinationCity: 'Mumbai (CSMIA)',
    distanceKm: 1148,
    weight: 0.28,
    dgcaPassengerSharePct: 28.0,
    isActive: true,
  },
  {
    id: 'route-2',
    code: 'DEL-BLR',
    origin: 'DEL',
    originCity: 'New Delhi (IGI)',
    destination: 'BLR',
    destinationCity: 'Bengaluru (KIA)',
    distanceKm: 1740,
    weight: 0.22,
    dgcaPassengerSharePct: 22.0,
    isActive: true,
  },
  {
    id: 'route-3',
    code: 'BOM-BLR',
    origin: 'BOM',
    originCity: 'Mumbai (CSMIA)',
    destination: 'BLR',
    destinationCity: 'Bengaluru (KIA)',
    distanceKm: 842,
    weight: 0.16,
    dgcaPassengerSharePct: 16.0,
    isActive: true,
  },
  {
    id: 'route-4',
    code: 'DEL-CCU',
    origin: 'DEL',
    originCity: 'New Delhi (IGI)',
    destination: 'CCU',
    destinationCity: 'Kolkata (NSCBI)',
    distanceKm: 1305,
    weight: 0.14,
    dgcaPassengerSharePct: 14.0,
    isActive: true,
  },
  {
    id: 'route-5',
    code: 'BLR-HYD',
    origin: 'BLR',
    originCity: 'Bengaluru (KIA)',
    destination: 'HYD',
    destinationCity: 'Hyderabad (RGIA)',
    distanceKm: 502,
    weight: 0.10,
    dgcaPassengerSharePct: 10.0,
    isActive: true,
  },
  {
    id: 'route-6',
    code: 'MAA-DEL',
    origin: 'MAA',
    originCity: 'Chennai (MAA)',
    destination: 'DEL',
    destinationCity: 'New Delhi (IGI)',
    distanceKm: 1760,
    weight: 0.10,
    dgcaPassengerSharePct: 10.0,
    isActive: true,
  },
];

export const AIRLINES: Airline[] = [
  {
    id: 'air-1',
    code: '6E',
    name: 'IndiGo',
    type: 'LCC',
    marketSharePct: 62.4,
    brandColor: '#0033A0',
    avgFareInr: 0,
    quoteCount: 0,
  },
  {
    id: 'air-2',
    code: 'AI',
    name: 'Air India',
    type: 'FSC',
    marketSharePct: 14.8,
    brandColor: '#D91C24',
    avgFareInr: 0,
    quoteCount: 0,
  },
  {
    id: 'air-3',
    code: 'IX',
    name: 'Air India Express',
    type: 'LCC',
    marketSharePct: 7.2,
    brandColor: '#F58220',
    avgFareInr: 0,
    quoteCount: 0,
  },
  {
    id: 'air-4',
    code: 'QP',
    name: 'Akasa Air',
    type: 'LCC',
    marketSharePct: 5.6,
    brandColor: '#FF671F',
    avgFareInr: 0,
    quoteCount: 0,
  },
  {
    id: 'air-5',
    code: 'SG',
    name: 'SpiceJet',
    type: 'LCC',
    marketSharePct: 4.1,
    brandColor: '#ED1C24',
    avgFareInr: 0,
    quoteCount: 0,
  },
];

export const DATA_SOURCES: DataSource[] = [
  {
    id: 'src-1',
    name: 'SerpApi (Google Flights)',
    type: 'API',
    ethicalStatus: 'COMPLIANT',
    rateLimitPerMin: 25,
    retryAttempts: 3,
    lastScraped: new Date().toISOString(),
    status: 'ONLINE',
    quotesToday: 0,
    captchaRespect: true,
  },
  {
    id: 'src-2',
    name: 'DataCrawler Google Flights (RapidAPI)',
    type: 'API',
    ethicalStatus: 'COMPLIANT',
    rateLimitPerMin: 20,
    retryAttempts: 3,
    lastScraped: new Date().toISOString(),
    status: 'ONLINE',
    quotesToday: 0,
    captchaRespect: true,
  },
  {
    id: 'src-3',
    name: 'MakeMyTrip (makemytrip.com)',
    type: 'OTA',
    ethicalStatus: 'COMPLIANT',
    rateLimitPerMin: 12,
    retryAttempts: 2,
    lastScraped: new Date().toISOString(),
    status: 'ONLINE',
    quotesToday: 0,
    captchaRespect: true,
  },
  {
    id: 'src-4',
    name: 'Goibibo (goibibo.com)',
    type: 'OTA',
    ethicalStatus: 'COMPLIANT',
    rateLimitPerMin: 12,
    retryAttempts: 2,
    lastScraped: new Date().toISOString(),
    status: 'ONLINE',
    quotesToday: 0,
    captchaRespect: true,
  },
  {
    id: 'src-5',
    name: 'Yatra (yatra.com)',
    type: 'OTA',
    ethicalStatus: 'COMPLIANT',
    rateLimitPerMin: 12,
    retryAttempts: 2,
    lastScraped: new Date().toISOString(),
    status: 'ONLINE',
    quotesToday: 0,
    captchaRespect: true,
  },
];

export const ADVANCE_WINDOWS: AdvanceWindow[] = ['T+1', 'T+7', 'T+15', 'T+30', 'T+45'];

export const BASE_ROUTE_FARES: Record<string, number> = {
  'DEL-BOM': 4750,
  'DEL-BLR': 5580,
  'BOM-BLR': 3950,
  'DEL-CCU': 4920,
  'BLR-HYD': 2980,
  'MAA-DEL': 5260,
};

export const AIRPORT_UDF: Record<string, number> = {
  DEL: 540,
  BOM: 490,
  BLR: 450,
  CCU: 380,
  HYD: 430,
  MAA: 360,
};
